[workspace]

members = [
    "cli",
    "common",
    "compiler",
    "gui",
]

[workspace.package]
authors = ["Rotbjorn"]
rust-version = "1.70"
edition = "2021"
repository = "https://github.com/Rotbjorn/matematisk"
readme = "README.md"