[package]
name = "matex-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.wasm32-unknown-unknown.dependencies]
serde = { version = "1.0.159", features = ["derive"]}